name: Update GIF

on:
  schedule:
    - cron: "0 0 21 3,6,9,12 *"
  workflow_dispatch: {}  # Manually trigger the workflow

jobs:
  update_gif:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # - name: Install dependencies
     # run: pip install -r requirements.txt

    - name: Update GIF
      run: python ./.github/workflows/season_picker.py
    - name: Switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: Check for changes
      run: git status
    - name: Push code to master
      run: 
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated report"
          git push

