name: Update GIF

on:
  schedule:
    - cron: "0 0 21 3,6,9,12 *"
  workflow_dispatch: {}  # Manually trigger the workflow

jobs:
  update_gif:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # - name: Install dependencies
     # run: pip install -r requirements.txt

    - name: Update GIF
      run: python ./github/workflows/season_picker.py
